/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iug;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectojava.AlimentoNatural;
import proyectojava.AlimentoProcesado;
import proyectojava.Lista;
import proyectojava.Proyecto1;

/**
 *
 * @author Bryan
 */
public class ConsultarAlimentoProcesado extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarAlimentoProcesado
     */
    public ConsultarAlimentoProcesado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        consultarProcesados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        coeliminar = new javax.swing.JTextField();
        eliminarProcesado = new javax.swing.JButton();
        actualizarProcesados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        codMXM = new javax.swing.JTextField();
        buscarPorCodigoP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fecMXM = new javax.swing.JSpinner();
        buscarPorFechaP = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Alimento Procesado");
        setLocationByPlatform(true);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        consultarProcesados.setText("Consultar");
        consultarProcesados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarProcesadosActionPerformed(evt);
            }
        });

        jLabel1.setText("Eliminar por codigo");

        eliminarProcesado.setText("Eliminar");
        eliminarProcesado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProcesadoActionPerformed(evt);
            }
        });

        actualizarProcesados.setText("Actualizar");
        actualizarProcesados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarProcesadosActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar por código");

        buscarPorCodigoP.setText("Buscar");
        buscarPorCodigoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorCodigoPActionPerformed(evt);
            }
        });

        jLabel3.setText("Buscar por fecha de creación");

        fecMXM.setModel(new javax.swing.SpinnerDateModel());
        fecMXM.setEditor(new javax.swing.JSpinner.DateEditor(fecMXM, "dd/MM/yyyy"));

        buscarPorFechaP.setText("Buscar");
        buscarPorFechaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorFechaPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(consultarProcesados)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actualizarProcesados)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(codMXM, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coeliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eliminarProcesado)
                                    .addComponent(buscarPorCodigoP)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(fecMXM, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarPorFechaP)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarProcesados)
                    .addComponent(actualizarProcesados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(coeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarProcesado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codMXM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPorCodigoP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fecMXM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPorFechaP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarProcesadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarProcesadosActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        jTable1.setModel(modelo);

        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Proteinas");
        modelo.addColumn("Carbohidratos");
        modelo.addColumn("Grasa");
        modelo.addColumn("Fecha");
        modelo.addColumn("Lista de ingredientes");

        for (int i = 0; i < Lista.procesados.size(); i++) {
            AlimentoProcesado alimento = Lista.procesados.get(i);

            modelo.addRow(new Object[]{alimento.getCodigo(),
                alimento.getNombre(), alimento.getProteinasPorCienGramos(),
                alimento.getCarbohidratosPorCienGramos(), alimento.getGrasasPorCienGramos(),
                alimento.getFechaCreacion(), alimento.getListaIngredientes()});
        }
    }//GEN-LAST:event_consultarProcesadosActionPerformed

    private void eliminarProcesadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProcesadoActionPerformed
        String codigo = coeliminar.getText().trim();
        boolean alimentoEncontrado = false; // Variable para indicar si se encontró el alimento

        for (int i = 0; i < Lista.procesados.size(); i++) {
            AlimentoProcesado alimento = Lista.procesados.get(i);
            if (alimento.getCodigo().equalsIgnoreCase(codigo)) {
                alimentoEncontrado = true;

                Proyecto1.GuardarDatos();
                Lista.procesados.remove(alimento);
                Proyecto1.archivoEliminado(alimento.getNombre());

                JOptionPane.showMessageDialog(null, "Alimento eliminado exitosamente.");
                coeliminar.setText("");

                break; // Salir del bucle una vez que se encuentra el alimento
            }
        }

        if (!alimentoEncontrado) {
            JOptionPane.showMessageDialog(null, "No se ha encontrado ningún código de alimento.");
            coeliminar.setText("");
        }
    }//GEN-LAST:event_eliminarProcesadoActionPerformed

    private void actualizarProcesadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarProcesadosActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        jTable1.setModel(modelo);

        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Proteinas");
        modelo.addColumn("Carbohidratos");
        modelo.addColumn("Grasa");
        modelo.addColumn("Fecha");
        modelo.addColumn("Lista de ingredientes");

        for (int i = 0; i < Lista.procesados.size(); i++) {
            AlimentoProcesado alimento = Lista.procesados.get(i);
            
            modelo.addRow(new Object[]{alimento.getCodigo(),
                alimento.getNombre(), alimento.getProteinasPorCienGramos(),
                alimento.getCarbohidratosPorCienGramos(), alimento.getGrasasPorCienGramos(),
                alimento.getFechaCreacion(), alimento.getListaIngredientes()});
        }
    }//GEN-LAST:event_actualizarProcesadosActionPerformed

    private void buscarPorCodigoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorCodigoPActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Limpiar los datos de la tabla antes de mostrar los resultados

        String codigoBuscado = codMXM.getText().trim();

        for (int i = 0; i < Lista.procesados.size(); i++) {
            AlimentoProcesado alimento = Lista.procesados.get(i);

            // Verificar si el código del alimento coincide con el código buscado
            if (alimento.getCodigo().equalsIgnoreCase(codigoBuscado)) {
                modelo.addRow(new Object[]{alimento.getCodigo(),
                    alimento.getNombre(), alimento.getProteinasPorCienGramos(),
                    alimento.getCarbohidratosPorCienGramos(), alimento.getGrasasPorCienGramos(),
                    alimento.getFechaCreacion(), alimento.getListaIngredientes()});
                codMXM.setText("");
            }
        }

        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No se encontraron alimentos con el código ingresado.");
            codMXM.setText("");
        }
    }//GEN-LAST:event_buscarPorCodigoPActionPerformed

    private void buscarPorFechaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorFechaPActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Limpiar los datos de la tabla antes de mostrar los resultados

        LocalDate fechaCreacionUsuario = ((Date) fecMXM.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        for (int i = 0; i < Lista.procesados.size(); i++) {
            AlimentoProcesado alimento = Lista.procesados.get(i);

            LocalDate fechaCreacionAlimento = alimento.getFechaCreacion().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            // Verificar si la fecha de creación del alimento coincide con la fecha ingresada por el usuario
            if (fechaCreacionAlimento.equals(fechaCreacionUsuario)) {
                modelo.addRow(new Object[]{alimento.getCodigo(),
                    alimento.getNombre(), alimento.getProteinasPorCienGramos(),
                    alimento.getCarbohidratosPorCienGramos(), alimento.getGrasasPorCienGramos(),
                    alimento.getFechaCreacion(), alimento.getListaIngredientes()});
            }
        }

        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No se encontraron alimentos con la fecha de creación ingresada.");
        }
    }//GEN-LAST:event_buscarPorFechaPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarAlimentoProcesado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarAlimentoProcesado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarAlimentoProcesado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarAlimentoProcesado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarAlimentoProcesado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarProcesados;
    private javax.swing.JButton buscarPorCodigoP;
    private javax.swing.JButton buscarPorFechaP;
    private javax.swing.JTextField codMXM;
    private javax.swing.JTextField coeliminar;
    private javax.swing.JButton consultarProcesados;
    private javax.swing.JButton eliminarProcesado;
    private javax.swing.JSpinner fecMXM;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
