/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iug;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectojava.AlimentoNatural;
import proyectojava.Lista;
import proyectojava.Proyecto1;

/**
 *
 * @author Bryan
 */
public class ConsultarAlimentoNatural extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarAlimentoNatural
     */
    public ConsultarAlimentoNatural() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        consultarNaturales = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        codeliminar = new javax.swing.JTextField();
        eliminarNatural = new javax.swing.JButton();
        actualizarNaturales = new javax.swing.JButton();
        fecTXT = new javax.swing.JSpinner();
        buscarPorFecha = new javax.swing.JLabel();
        buscarPorFechaN = new javax.swing.JButton();
        buscarPorCodigo = new javax.swing.JLabel();
        codTXT = new javax.swing.JTextField();
        buscarPorCodigoN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Alimento Natural");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        consultarNaturales.setText("Consultar");
        consultarNaturales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarNaturalesActionPerformed(evt);
            }
        });

        jLabel1.setText("Eliminar por código ");

        codeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeliminarActionPerformed(evt);
            }
        });

        eliminarNatural.setText("Eliminar");
        eliminarNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarNaturalActionPerformed(evt);
            }
        });

        actualizarNaturales.setText("Actualizar");
        actualizarNaturales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarNaturalesActionPerformed(evt);
            }
        });

        fecTXT.setModel(new javax.swing.SpinnerDateModel());
        fecTXT.setEditor(new javax.swing.JSpinner.DateEditor(fecTXT, "dd/MM/yyyy"));

        buscarPorFecha.setText("Buscar por fecha de creacíon");

        buscarPorFechaN.setText("Buscar");
        buscarPorFechaN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorFechaNActionPerformed(evt);
            }
        });

        buscarPorCodigo.setText("Buscar por código");

        buscarPorCodigoN.setText("Buscar");
        buscarPorCodigoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorCodigoNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(consultarNaturales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(actualizarNaturales))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(buscarPorFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fecTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarPorFechaN))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eliminarNatural))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscarPorCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarPorCodigoN)))
                        .addGap(134, 134, 134)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarNaturales)
                    .addComponent(actualizarNaturales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarNatural))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPorCodigo)
                    .addComponent(buscarPorCodigoN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPorFechaN)
                    .addComponent(buscarPorFecha))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarNaturalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarNaturalesActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        jTable1.setModel(modelo);

        modelo.addColumn("Tipo");
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Proteinas");
        modelo.addColumn("Carbohidratos");
        modelo.addColumn("Grasa");
        modelo.addColumn("Fecha");

        for (int i = 0; i < Lista.naturales.size(); i++) {
            AlimentoNatural alimento = Lista.naturales.get(i);
         
                modelo.addRow(new Object[]{alimento.getTipoAlimento(), alimento.getCodigo(),
                    alimento.getNombre(), alimento.getProteinasPorCienGramos(),
                    alimento.getCarbohidratosPorCienGramos(), alimento.getGrasasPorCienGramos(),
                    alimento.getFechaCreacion()});
        }
    }//GEN-LAST:event_consultarNaturalesActionPerformed

    private void eliminarNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarNaturalActionPerformed
        String codigo = codeliminar.getText().trim();
        boolean alimentoEncontrado = false; // Variable para indicar si se encontró el alimento

        for (int i = 0; i < Lista.naturales.size(); i++) {
            AlimentoNatural alimento = Lista.naturales.get(i);
            if (alimento.getCodigo().equalsIgnoreCase(codigo)) {
                alimentoEncontrado = true;

                Proyecto1.GuardarDatos();
                Lista.naturales.remove(alimento);
                Proyecto1.archivoEliminado(alimento.getNombre());

                JOptionPane.showMessageDialog(null, "Alimento eliminado exitosamente.");
                codeliminar.setText("");

                break; // Salir del bucle una vez que se encuentra el alimento
            }
        }

        if (!alimentoEncontrado) {
            JOptionPane.showMessageDialog(null, "No se ha encontrado ningún código de alimento.");
            codeliminar.setText("");
        }


    }//GEN-LAST:event_eliminarNaturalActionPerformed

    private void codeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeliminarActionPerformed
  
    }//GEN-LAST:event_codeliminarActionPerformed

    private void actualizarNaturalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarNaturalesActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        jTable1.setModel(modelo);

        modelo.addColumn("Tipo");
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Proteinas");
        modelo.addColumn("Carbohidratos");
        modelo.addColumn("Grasa");
        modelo.addColumn("Fecha");

        for (int i = 0; i < Lista.naturales.size(); i++) {
            AlimentoNatural alimento = Lista.naturales.get(i);
                modelo.addRow(new Object[]{alimento.getTipoAlimento(), alimento.getCodigo(),
                    alimento.getNombre(), alimento.getProteinasPorCienGramos(),
                    alimento.getCarbohidratosPorCienGramos(), alimento.getGrasasPorCienGramos(),
                    alimento.getFechaCreacion()});
            }
    }//GEN-LAST:event_actualizarNaturalesActionPerformed

    private void buscarPorFechaNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorFechaNActionPerformed

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Limpiar los datos de la tabla antes de mostrar los resultados

        LocalDate fechaCreacionUsuario = ((Date) fecTXT.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        for (int i = 0; i < Lista.naturales.size(); i++) {
            AlimentoNatural alimento = Lista.naturales.get(i);

            LocalDate fechaCreacionAlimento = alimento.getFechaCreacion().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            // Verificar si la fecha de creación del alimento coincide con la fecha ingresada por el usuario
            if (fechaCreacionAlimento.equals(fechaCreacionUsuario)) {
                modelo.addRow(new Object[]{alimento.getTipoAlimento(), alimento.getCodigo(),
                    alimento.getNombre(), alimento.getProteinasPorCienGramos(),
                    alimento.getCarbohidratosPorCienGramos(), alimento.getGrasasPorCienGramos(),
                    alimento.getFechaCreacion()});
            }
        }

        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No se encontraron alimentos con la fecha de creación ingresada.");
        }
    }//GEN-LAST:event_buscarPorFechaNActionPerformed

    private void buscarPorCodigoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorCodigoNActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Limpiar los datos de la tabla antes de mostrar los resultados

        String codigoBuscado = codTXT.getText().trim();

        for (int i = 0; i < Lista.naturales.size(); i++) {
            AlimentoNatural alimento = Lista.naturales.get(i);

            // Verificar si el código del alimento coincide con el código buscado
            if (alimento.getCodigo().equalsIgnoreCase(codigoBuscado)) {
                modelo.addRow(new Object[]{alimento.getTipoAlimento(), alimento.getCodigo(),
                    alimento.getNombre(), alimento.getProteinasPorCienGramos(),
                    alimento.getCarbohidratosPorCienGramos(), alimento.getGrasasPorCienGramos(),
                    alimento.getFechaCreacion()});
                codTXT.setText("");
            }
        }

        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No se encontraron alimentos con el código ingresado.");
        }
    }//GEN-LAST:event_buscarPorCodigoNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarAlimentoNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarAlimentoNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarAlimentoNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarAlimentoNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarAlimentoNatural().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarNaturales;
    private javax.swing.JLabel buscarPorCodigo;
    private javax.swing.JButton buscarPorCodigoN;
    private javax.swing.JLabel buscarPorFecha;
    private javax.swing.JButton buscarPorFechaN;
    private javax.swing.JTextField codTXT;
    private javax.swing.JTextField codeliminar;
    private javax.swing.JButton consultarNaturales;
    private javax.swing.JButton eliminarNatural;
    private javax.swing.JSpinner fecTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
