/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iug;

import java.awt.HeadlessException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectojava.AlimentoNatural;
import proyectojava.AlimentoProcesado;
import proyectojava.Lista;
import proyectojava.Proyecto1;

/**
 *
 * @author Bryan
 */
public class RegistroAlimentoNatural extends javax.swing.JFrame {

    private String tipoAlimento;
    private Date fechaCreacion;
    private javax.swing.JTable jTable1;

    /**
     * Creates new form RegistroAlimentoNatural
     */
    public RegistroAlimentoNatural() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codTXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        proteTXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        carbTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        grasTXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        guardarNatural = new javax.swing.JButton();
        tipoTXT = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        fecTXT = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        buscarNatural = new javax.swing.JButton();
        ActualizarNatural = new javax.swing.JButton();
        consultarNatural = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alimento Natural");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setText("Código del alimento");

        jLabel2.setText("Nombre del alimento");

        jLabel3.setText("Cantidad de proteínas por cada 100 gramos");

        jLabel4.setText("Cantidad de carbohidratos por cada 100 gramos");

        jLabel5.setText("Cantidad de grasas por cada 100 gramos");

        jLabel6.setText("Tipo de alimento");

        guardarNatural.setText("Guardar");
        guardarNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarNaturalActionPerformed(evt);
            }
        });

        tipoTXT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruta", "Verdura", "Cereal", "Carne" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Registro de Alimento Natural");

        fecTXT.setModel(new javax.swing.SpinnerDateModel());
        fecTXT.setEditor(new javax.swing.JSpinner.DateEditor(fecTXT, "dd/MM/yyyy"));

        jLabel8.setText("Fecha de creación");

        buscarNatural.setText("Buscar por código");
        buscarNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNaturalActionPerformed(evt);
            }
        });

        ActualizarNatural.setText("Actualizar");
        ActualizarNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarNaturalActionPerformed(evt);
            }
        });

        consultarNatural.setText("Consulltar");
        consultarNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarNaturalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(carbTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(proteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(buscarNatural)
                        .addGap(18, 18, 18)
                        .addComponent(ActualizarNatural)
                        .addGap(18, 18, 18)
                        .addComponent(consultarNatural)
                        .addGap(18, 18, 18)
                        .addComponent(guardarNatural))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecTXT))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(grasTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tipoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(proteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(carbTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(grasTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarNatural)
                    .addComponent(ActualizarNatural)
                    .addComponent(consultarNatural)
                    .addComponent(guardarNatural))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarNaturalActionPerformed

        try {
            String tipoAlimento = tipoTXT.getSelectedItem().toString();
            String codigo = codTXT.getText().trim();
            String nombre = nomTXT.getText().trim();
            String proteinasPorCienGramosTexto = proteTXT.getText().trim();
            double proteinasDouble = Double.parseDouble(proteinasPorCienGramosTexto);
            String carbohidratosPorCienGramosTexto = carbTXT.getText().trim();
            double carbohidratosDouble = Double.parseDouble(carbohidratosPorCienGramosTexto);
            String grasasPorCienGramosTexto = grasTXT.getText().trim();
            double grasasDouble = Double.parseDouble(grasasPorCienGramosTexto);
            Date fechaCreacion = (Date) fecTXT.getValue();

            if (codigo.isEmpty() || nombre.isEmpty() || proteinasPorCienGramosTexto.isEmpty()
                    || carbohidratosPorCienGramosTexto.isEmpty() || grasasPorCienGramosTexto.isEmpty()) {

            } else {

                boolean codigoExiste = false;
                for (AlimentoNatural alimentoExistente : Lista.naturales) {
                    if (alimentoExistente.getCodigo().equalsIgnoreCase(codigo)) {
                        codigoExiste = true;
                        break;
                    }
                }
                if (codigoExiste) {
                    JOptionPane.showMessageDialog(null, "Ya existe un alimento con el mismo código. Por favor, ingresa un código distinto.");
                } else {
                    AlimentoNatural alimento = new AlimentoNatural(tipoAlimento, codigo, nombre, proteinasDouble, carbohidratosDouble, grasasDouble, (Date) fechaCreacion);
                    Lista.naturales.add(alimento);
                    Proyecto1.GuardarDatos();
                    JOptionPane.showMessageDialog(null, "Datos almacenados exitosamente.");
                    codTXT.setText("");
                    nomTXT.setText("");
                    proteTXT.setText("");
                    carbTXT.setText("");
                    grasTXT.setText("");

                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos vacíos. Por favor, completa todos los campos.");

        }

    }//GEN-LAST:event_guardarNaturalActionPerformed

    private void buscarNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNaturalActionPerformed
        String codigo = codTXT.getText().trim();
        boolean alimentoEncontrado = false; // Variable para indicar si se encontró el alimento

        for (int i = 0; i < Lista.naturales.size(); i++) {
            AlimentoNatural alimento = Lista.naturales.get(i);
           
                if (alimento.getCodigo().equalsIgnoreCase(codigo)) {
                    alimentoEncontrado = true;

                    JOptionPane.showMessageDialog(null, "Alimento encontrado");

                    tipoTXT.setSelectedItem(alimento.getTipoAlimento() + "");
                    codTXT.setText(alimento.getCodigo() + "");
                    nomTXT.setText(alimento.getNombre() + "");
                    proteTXT.setText(alimento.getProteinasPorCienGramos() + "");
                    carbTXT.setText(alimento.getCarbohidratosPorCienGramos() + "");
                    grasTXT.setText(alimento.getGrasasPorCienGramos() + "");
                    fecTXT.setValue(alimento.getFechaCreacion());

                    break; // Salir del bucle una vez que se encuentra el alimento
                }
            
        }

        if (!alimentoEncontrado) {
            JOptionPane.showMessageDialog(null, "No se ha encontrado ningún código de alimento.");
            codTXT.setText("");
        }
       

    }//GEN-LAST:event_buscarNaturalActionPerformed

    private void ActualizarNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarNaturalActionPerformed
        try {

            String tipoAlimento = tipoTXT.getSelectedItem().toString();
            String codigo = codTXT.getText().trim();
            String nombre = nomTXT.getText().trim();
            String proteinasPorCienGramosTexto = proteTXT.getText().trim();
            double proteinasDouble = Double.parseDouble(proteinasPorCienGramosTexto);
            String carbohidratosPorCienGramosTexto = carbTXT.getText().trim();
            double carbohidratosDouble = Double.parseDouble(carbohidratosPorCienGramosTexto);
            String grasasPorCienGramosTexto = grasTXT.getText().trim();
            double grasasDouble = Double.parseDouble(grasasPorCienGramosTexto);
            Date fechaCreacion = (Date) fecTXT.getValue();

            if (codigo.isEmpty() || nombre.isEmpty() || proteinasPorCienGramosTexto.isEmpty()
                    || carbohidratosPorCienGramosTexto.isEmpty() || grasasPorCienGramosTexto.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Hay datos vacíos. Por favor, completa todos los campos.");
            } else {

                Proyecto1.GuardarDatos();
                codTXT.setText("");
                nomTXT.setText("");
                proteTXT.setText("");
                carbTXT.setText("");
                grasTXT.setText("");

                for (int i = 0; i < Lista.naturales.size(); i++) {
                    AlimentoNatural alimento = Lista.naturales.get(i);
                   
                    if (alimento.getCodigo().equalsIgnoreCase(codigo)) {

                        alimento.setTipoAlimento(tipoAlimento);
                        alimento.setCodigo(codigo);
                        alimento.setNombre(nombre);
                        alimento.setProteinasPorCienGramos(proteinasDouble);
                        alimento.setCarbohidratosPorCienGramos(carbohidratosDouble);
                        alimento.setGrasasPorCienGramos(grasasDouble);
                        alimento.setFechaCreacion(fechaCreacion);
                        Proyecto1.GuardarDatos();

                        JOptionPane.showMessageDialog(null, "Alimento actualizado");

                        //Proyecto1.archivoEliminado(codeliminar.getText());
                    }
                    
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos vacíos. Por favor, completa todos los campos.");

        }
    }//GEN-LAST:event_ActualizarNaturalActionPerformed

    private void consultarNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarNaturalActionPerformed
        ConsultarAlimentoNatural registro = new ConsultarAlimentoNatural();
        registro.setVisible(true);
    }//GEN-LAST:event_consultarNaturalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAlimentoNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAlimentoNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAlimentoNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAlimentoNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAlimentoNatural().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarNatural;
    private javax.swing.JButton buscarNatural;
    private javax.swing.JTextField carbTXT;
    private javax.swing.JTextField codTXT;
    private javax.swing.JButton consultarNatural;
    private javax.swing.JSpinner fecTXT;
    private javax.swing.JTextField grasTXT;
    private javax.swing.JButton guardarNatural;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nomTXT;
    private javax.swing.JTextField proteTXT;
    private javax.swing.JComboBox<String> tipoTXT;
    // End of variables declaration//GEN-END:variables
}
