/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iug;

import java.awt.HeadlessException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import proyectojava.AlimentoNatural;
import proyectojava.AlimentoProcesado;
import proyectojava.Lista;
import proyectojava.Proyecto1;

/**
 *
 * @author Bryan
 */
public class RegistroAlimentoProcesado extends javax.swing.JFrame {

    /**
     * Creates new form RegistroAlimentoProcesado
     */
    public RegistroAlimentoProcesado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codMXM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namMXM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        proteMXM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        carbMXM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        grasMXM = new javax.swing.JTextField();
        guardarProcesado = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMXM = new javax.swing.JTextArea();
        fecMXM = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        consultarProcesado = new javax.swing.JButton();
        ActualizarProcesado = new javax.swing.JButton();
        buscarProcesado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alimento Procesado");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setText("Código del alimento");

        jLabel2.setText("Nombre del alimento");

        jLabel3.setText("Cantidad de proteínas por cada 100 gramos");

        jLabel4.setText("Cantidad de carbohidratos por cada 100 gramos");

        jLabel5.setText("Cantidad de grasas por cada 100 gramos");

        guardarProcesado.setText("Guardar");
        guardarProcesado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarProcesadoActionPerformed(evt);
            }
        });

        jLabel6.setText("Lista de ingredientes");

        listMXM.setColumns(20);
        listMXM.setRows(5);
        jScrollPane1.setViewportView(listMXM);

        fecMXM.setModel(new javax.swing.SpinnerDateModel());
        fecMXM.setEditor(new javax.swing.JSpinner.DateEditor(fecMXM, "dd/MM/yyyy"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Registro de Alimentos Procesados");

        jLabel8.setText("Fecha de creación");

        consultarProcesado.setText("Consultar");
        consultarProcesado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarProcesadoActionPerformed(evt);
            }
        });

        ActualizarProcesado.setText("Actualizar");
        ActualizarProcesado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarProcesadoActionPerformed(evt);
            }
        });

        buscarProcesado.setText("Buscar por código");
        buscarProcesado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProcesadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fecMXM, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grasMXM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(proteMXM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(namMXM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(carbMXM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codMXM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscarProcesado)
                                .addGap(18, 18, 18)
                                .addComponent(ActualizarProcesado)
                                .addGap(18, 18, 18)
                                .addComponent(consultarProcesado)
                                .addGap(18, 18, 18)
                                .addComponent(guardarProcesado)))))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codMXM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namMXM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(proteMXM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(carbMXM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grasMXM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fecMXM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarProcesado)
                    .addComponent(consultarProcesado)
                    .addComponent(ActualizarProcesado)
                    .addComponent(buscarProcesado))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarProcesadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarProcesadoActionPerformed
        try {
            String ingredientes = listMXM.getText().trim();
            String codigo = codMXM.getText().trim();
            String nombre = namMXM.getText().trim();
            String proteinasPorCienGramosTexto = proteMXM.getText().trim();
            double proteinasDouble = Double.parseDouble(proteinasPorCienGramosTexto);
            String carbohidratosPorCienGramosTexto = carbMXM.getText().trim();
            double carbohidratosDouble = Double.parseDouble(carbohidratosPorCienGramosTexto);
            String grasasPorCienGramosTexto = grasMXM.getText().trim();
            double grasasDouble = Double.parseDouble(grasasPorCienGramosTexto);
            Date fechaCreacion = (Date) fecMXM.getValue();

            if (codigo.isEmpty() || nombre.isEmpty() || proteinasPorCienGramosTexto.isEmpty()
                    || carbohidratosPorCienGramosTexto.isEmpty() || grasasPorCienGramosTexto.isEmpty() || ingredientes.isEmpty()) {

            } else {

                boolean codigoExiste = false;
                for (AlimentoProcesado alimentoExistente : Lista.procesados) {
                    if (alimentoExistente.getCodigo().equalsIgnoreCase(codigo)) {
                        codigoExiste = true;
                        break;
                    }
                }
                if (codigoExiste) {
                    JOptionPane.showMessageDialog(null, "Ya existe un alimento con el mismo código. Por favor, ingresa un código distinto.");
                } else {
                    AlimentoProcesado alimento = new AlimentoProcesado(codigo, nombre, proteinasDouble, carbohidratosDouble, grasasDouble, (Date)fechaCreacion, ingredientes);
                    Lista.procesados.add(alimento);
                    Proyecto1.GuardarDatos();
                    JOptionPane.showMessageDialog(null, "Datos almacenados exitosamente.");
                    codMXM.setText("");
                    namMXM.setText("");
                    proteMXM.setText("");
                    carbMXM.setText("");
                    grasMXM.setText("");
                    listMXM.setText("");

                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos vacíos. Por favor, completa todos los campos.");

        }

    }//GEN-LAST:event_guardarProcesadoActionPerformed

    private void consultarProcesadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarProcesadoActionPerformed
        ConsultarAlimentoProcesado registro = new ConsultarAlimentoProcesado();
        registro.setVisible(true);
    }//GEN-LAST:event_consultarProcesadoActionPerformed

    private void buscarProcesadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProcesadoActionPerformed
         String codigo = codMXM.getText().trim();
        boolean alimentoEncontrado = false; // Variable para indicar si se encontró el alimento

        for (int i = 0; i < Lista.procesados.size(); i++) {
            AlimentoProcesado alimento = Lista.procesados.get(i);
            
                if (alimento.getCodigo().equalsIgnoreCase(codigo)) {
                    alimentoEncontrado = true;

                    JOptionPane.showMessageDialog(null, "Alimento encontrado");

                    String ingredientes = listMXM.getText().trim();
                    codMXM.setText(alimento.getCodigo() + "");
                    namMXM.setText(alimento.getNombre() + "");
                    proteMXM.setText(alimento.getProteinasPorCienGramos() + "");
                    carbMXM.setText(alimento.getCarbohidratosPorCienGramos() + "");
                    grasMXM.setText(alimento.getGrasasPorCienGramos() + "");
                    fecMXM.setValue(alimento.getFechaCreacion());

                    break; // Salir del bucle una vez que se encuentra el alimento
                }
            
        }

        if (!alimentoEncontrado) {
            JOptionPane.showMessageDialog(null, "No se ha encontrado ningún código de alimento.");
            codMXM.setText("");
        }
    }//GEN-LAST:event_buscarProcesadoActionPerformed

    private void ActualizarProcesadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarProcesadoActionPerformed
                try {

            String ingredientes = listMXM.getText().trim();
            String codigo = codMXM.getText().trim();
            String nombre = namMXM.getText().trim();
            String proteinasPorCienGramosTexto = proteMXM.getText().trim();
            double proteinasDouble = Double.parseDouble(proteinasPorCienGramosTexto);
            String carbohidratosPorCienGramosTexto = carbMXM.getText().trim();
            double carbohidratosDouble = Double.parseDouble(carbohidratosPorCienGramosTexto);
            String grasasPorCienGramosTexto = grasMXM.getText().trim();
            double grasasDouble = Double.parseDouble(grasasPorCienGramosTexto);
            Date fechaCreacion = (Date) fecMXM.getValue();

            if (codigo.isEmpty() || nombre.isEmpty() || proteinasPorCienGramosTexto.isEmpty()
                    || carbohidratosPorCienGramosTexto.isEmpty() || grasasPorCienGramosTexto.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Hay datos vacíos. Por favor, completa todos los campos.");
            } else {

                Proyecto1.GuardarDatos();
                codMXM.setText("");
                namMXM.setText("");
                proteMXM.setText("");
                carbMXM.setText("");
                grasMXM.setText("");
                listMXM.setText("");

                for (int i = 0; i < Lista.procesados.size(); i++) {
                    AlimentoProcesado alimento = Lista.procesados.get(i);
             
                    if (alimento.getCodigo().equalsIgnoreCase(codigo)) {

                        alimento.setListaIngredientes(ingredientes);
                        alimento.setCodigo(codigo);
                        alimento.setNombre(nombre);
                        alimento.setProteinasPorCienGramos(proteinasDouble);
                        alimento.setCarbohidratosPorCienGramos(carbohidratosDouble);
                        alimento.setGrasasPorCienGramos(grasasDouble);
                        alimento.setFechaCreacion(fechaCreacion);
                        Proyecto1.GuardarDatos();

                        JOptionPane.showMessageDialog(null, "Alimento actualizado");

                        //Proyecto1.archivoEliminado(codeliminar.getText());
                    }
                  
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos vacíos. Por favor, completa todos los campos.");

        }
    }//GEN-LAST:event_ActualizarProcesadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAlimentoProcesado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAlimentoProcesado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAlimentoProcesado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAlimentoProcesado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAlimentoProcesado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarProcesado;
    private javax.swing.JButton buscarProcesado;
    private javax.swing.JTextField carbMXM;
    private javax.swing.JTextField codMXM;
    private javax.swing.JButton consultarProcesado;
    private javax.swing.JSpinner fecMXM;
    private javax.swing.JTextField grasMXM;
    private javax.swing.JButton guardarProcesado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listMXM;
    private javax.swing.JTextField namMXM;
    private javax.swing.JTextField proteMXM;
    // End of variables declaration//GEN-END:variables
}
